sonar.projectKey=mip
sonar.projectName=MIP
sonar.projectVersion=1.6

sonar.sources=bin,lib
sonar.exclusions=**/node_modules/**,**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.exclusions=**/node_modules/**,**/*.test.js